spring:
  profiles: prod
app:
  name: himanshu_prod_from_yml_new

---

spring:
  profiles: staging
app:
  name: himanshu_staging_from_yml_new
  
---

spring:
  profiles: dev
app:
  name: himanshu_dev_from_yml_new_property
